"""unidosis 2

Revision ID: 1706d740a3ac
Revises: 659ab765a6ce
Create Date: 2023-09-12 22:02:11.406232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1706d740a3ac'
down_revision: Union[str, None] = '659ab765a6ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_unidosismedicine_id', table_name='unidosismedicine')
    op.drop_table('unidosismedicine')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unidosismedicine',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('update_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('code', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('drug', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('concentration', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('form', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('gtin', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('visual_config1', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('visual_config2', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('visual_config3', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('visual_config4', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('adv1', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('adv2', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('adv3', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('adv4', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('adv5', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('tac', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('pregnancy_cat', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='unidosismedicine_pkey')
    )
    op.create_index('ix_unidosismedicine_id', 'unidosismedicine', ['id'], unique=False)
    # ### end Alembic commands ###
