"""Second migration

Revision ID: 43d8a04d05a2
Revises: 8c01c48f475e
Create Date: 2023-09-10 15:24:51.568487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '43d8a04d05a2'
down_revision: Union[str, None] = '8c01c48f475e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.Column('personal_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('lastname', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('birthdate', sa.Date(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('medicine', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('medicine', sa.Column('update_at', sa.DateTime(), nullable=False))
    op.add_column('patient', sa.Column('personal_id', sa.Integer(), nullable=False))
    op.add_column('patient', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('patient', sa.Column('lastname', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('patient', sa.Column('birthdate', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patient', 'birthdate')
    op.drop_column('patient', 'lastname')
    op.drop_column('patient', 'name')
    op.drop_column('patient', 'personal_id')
    op.drop_column('medicine', 'update_at')
    op.drop_column('medicine', 'created_at')
    op.drop_table('doctor')
    # ### end Alembic commands ###
