"""4 migration

Revision ID: 445192c7884c
Revises: 9ec6d3749192
Create Date: 2023-09-11 19:16:27.595891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '445192c7884c'
down_revision: Union[str, None] = '9ec6d3749192'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prescriptiondetails', sa.Column('medicine_id', sa.Integer(), nullable=False))
    op.add_column('prescriptiondetails', sa.Column('qty', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'prescriptiondetails', 'medicine', ['medicine_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'prescriptiondetails', type_='foreignkey')
    op.drop_column('prescriptiondetails', 'qty')
    op.drop_column('prescriptiondetails', 'medicine_id')
    # ### end Alembic commands ###
