"""accees_levels

Revision ID: 49982d7e6fea
Revises: e49b097b8ffc
Create Date: 2023-09-28 19:41:00.897959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '49982d7e6fea'
down_revision: Union[str, None] = 'e49b097b8ffc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('access_level', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default="USER"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'access_level')
    # ### end Alembic commands ###
