"""4er migration

Revision ID: 4a77b65f6ef1
Revises: 9b6b025b773a
Create Date: 2023-09-10 23:19:43.762292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4a77b65f6ef1'
down_revision: Union[str, None] = '9b6b025b773a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('prescriptiondetails_medicine_id_fkey', 'prescriptiondetails', type_='foreignkey')
    op.drop_column('prescriptiondetails', 'medicine_id')
    op.drop_column('prescriptiondetails', 'qty')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prescriptiondetails', sa.Column('qty', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('prescriptiondetails', sa.Column('medicine_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('prescriptiondetails_medicine_id_fkey', 'prescriptiondetails', 'medicine', ['medicine_id'], ['id'])
    # ### end Alembic commands ###
