"""prueba

Revision ID: 4fd55c675247
Revises: ee6e7809f3a0
Create Date: 2023-10-03 20:41:46.022490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4fd55c675247'
down_revision: Union[str, None] = 'ee6e7809f3a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('access_level', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=False)
    op.create_table('unidosismedicine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.Column('visual_config1', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('visual_config2', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('visual_config3', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('visual_config4', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('adv1', sa.Boolean(), nullable=True),
    sa.Column('adv2', sa.Boolean(), nullable=True),
    sa.Column('adv3', sa.Boolean(), nullable=True),
    sa.Column('adv4', sa.Boolean(), nullable=True),
    sa.Column('adv5', sa.Boolean(), nullable=True),
    sa.Column('tac', sa.Boolean(), nullable=True),
    sa.Column('pregnancy_cat', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('medicine_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicine.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unidosismedicine_id'), 'unidosismedicine', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_unidosismedicine_id'), table_name='unidosismedicine')
    op.drop_table('unidosismedicine')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
