"""agregado de unidosis en nuevo modelo

Revision ID: 5ff7f2faa944
Revises: 38535c2b6add
Create Date: 2023-09-12 21:04:57.738911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5ff7f2faa944'
down_revision: Union[str, None] = '38535c2b6add'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
