"""Initial migration

Revision ID: 8c01c48f475e
Revises: 
Create Date: 2023-09-10 12:19:37.087743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8c01c48f475e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medicine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('drug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('concentration', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('form', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gtin', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medicine_id'), 'medicine', ['id'], unique=False)
    op.create_table('patient',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patient')
    op.drop_index(op.f('ix_medicine_id'), table_name='medicine')
    op.drop_table('medicine')
    # ### end Alembic commands ###
