"""3er migration

Revision ID: 9b6b025b773a
Revises: 73dace2f5869
Create Date: 2023-09-10 17:35:25.987183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9b6b025b773a'
down_revision: Union[str, None] = '73dace2f5869'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor', sa.Column('code', sa.Integer(), nullable=True))
    op.add_column('medicine', sa.Column('code', sa.Integer(), nullable=True))
    op.add_column('patient', sa.Column('code', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patient', 'code')
    op.drop_column('medicine', 'code')
    op.drop_column('doctor', 'code')
    # ### end Alembic commands ###
