"""unidosis 4

Revision ID: c3813cf9dff5
Revises: e71bf1777af4
Create Date: 2023-09-12 22:40:21.074483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c3813cf9dff5'
down_revision: Union[str, None] = 'e71bf1777af4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unidosismedicine', sa.Column('medicine_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'unidosismedicine', 'medicine', ['medicine_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'unidosismedicine', type_='foreignkey')
    op.drop_column('unidosismedicine', 'medicine_id')
    # ### end Alembic commands ###
