"""accees_levels2

Revision ID: d410fd756592
Revises: 49982d7e6fea
Create Date: 2023-09-29 21:18:04.796159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd410fd756592'
down_revision: Union[str, None] = '49982d7e6fea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_doctor')
    op.drop_column('user', 'is_admin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_admin', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('is_doctor', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
