"""unidosis 3

Revision ID: e71bf1777af4
Revises: fc24a9a8197b
Create Date: 2023-09-12 22:08:52.220474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e71bf1777af4'
down_revision: Union[str, None] = 'fc24a9a8197b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unidosismedicine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.Column('visual_config1', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('visual_config2', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('visual_config3', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('visual_config4', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('adv1', sa.Boolean(), nullable=True),
    sa.Column('adv2', sa.Boolean(), nullable=True),
    sa.Column('adv3', sa.Boolean(), nullable=True),
    sa.Column('adv4', sa.Boolean(), nullable=True),
    sa.Column('adv5', sa.Boolean(), nullable=True),
    sa.Column('tac', sa.Boolean(), nullable=True),
    sa.Column('pregnancy_cat', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unidosismedicine_id'), 'unidosismedicine', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_unidosismedicine_id'), table_name='unidosismedicine')
    op.drop_table('unidosismedicine')
    # ### end Alembic commands ###
